Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/AsciiComments:
  Enabled: false

Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition

Style/MutableConstant:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/MultilineMethodCallIndentation:
  Enabled: false
